
# Makefile for genplus SDL
#
# (c) 1999, 2000, 2001, 2002, 2003  Charles MacDonald
# modified by Eke-Eke <eke_eke31@yahoo.fr>
#
# Defines :
# -DLSB_FIRST : for little endian systems.
# -DLOGERROR  : enable message logging
# -DLOGVDP    : enable VDP debug messages
# -DLOGSOUND  : enable AUDIO debug messages
# -DLOG_SCD   : enable SCD debug messages
# -DLOG_CDD   : enable CDD debug messages
# -DLOG_CDC   : enable CDC debug messages
# -DLOG_PCM   : enable PCM debug messages
# -DLOGSOUND  : enable AUDIO debug messages
# -D8BPP_RENDERING  - configure for 8-bit pixels (RGB332)
# -D15BPP_RENDERING - configure for 15-bit pixels (RGB555)
# -D16BPP_RENDERING - configure for 16-bit pixels (RGB565)
# -D32BPP_RENDERING - configure for 32-bit pixels (RGB888)
# -DUSE_LIBCHDR      : enable CHD file support
# -DUSE_LIBTREMOR    : enable OGG file support for CD emulation using provided TREMOR library
# -DUSE_LIBVORBIS    : enable OGG file support for CD emulation using external VORBIS library
# -DISABLE_MANY_OGG_OPEN_FILES : only have one OGG file opened at once to save RAM
# -DMAXROMSIZE       : defines maximal size of ROM buffer (also shared with CD hardware)
# -DHAVE_YM3438_CORE : enable (configurable) support for Nuked cycle-accurate YM2612/YM3438 core
# -DHAVE_OPLL_CORE   : enable (configurable) support for Nuked cycle-accurate YM2413 core
# -DHOOK_CPU         : enable CPU hooks
# -DENABLE_SUB_68K_ADDRESS_ERROR_EXCEPTIONS : enable address error exceptions emulation for SUB-CPU

BIN	  = gen_sdl

CC        = gcc
CXX       = g++

CFLAGS    = `sdl-config --cflags` -march=native -O6 -fomit-frame-pointer -Wall -Wno-strict-aliasing -std=c99 -pedantic-errors

CXXFLAGS    = `sdl-config --cflags` -march=native -O6 -fomit-frame-pointer -Wall -Wno-strict-aliasing -std=c++98 
#-pedantic-errors

#-g -ggdb -pg
#-fomit-frame-pointer
#LDFLAGS   = -pg
DEFINES   = -DLSB_FIRST -DUSE_16BPP_RENDERING -DUSE_LIBTREMOR -DUSE_LIBCHDRX -DMAXROMSIZE_=33554432 -DHAVE_YM3438_CORE -DHAVE_OPLL_CORE -DENABLE_SUB_68K_ADDRESS_ERROR_EXCEPTIONS -DZ7_ST -DZSTD_DISABLE_ASM -DHAVE_STB_TRUETYPE

DEFINES += -DMAXROMSIZE=0x900000 -DENABLE_SEGACD -DENABLE_SEGAMD
ENABLE_CDS = 1
 

#DEFINES += -DUSE_DYNAMIC_ALLOC -DDISABLE_MANY_OGG_OPEN_FILES

ifneq ($(OS),Windows_NT)
DEFINES += -DHAVE_ALLOCA_H
endif

SRCDIR    = Genesis-Plus-GX-master/core
INCLUDES  = -I. -I$(SRCDIR) -I$(SRCDIR)/z80 -I$(SRCDIR)/m68k -I$(SRCDIR)/sound -I$(SRCDIR)/sound/minimp3 -I$(SRCDIR)/sound/tremor -I$(SRCDIR)/input_hw -I$(SRCDIR)/cart_hw -I$(SRCDIR)/cart_hw/svp -I$(SRCDIR)/cd_hw -I$(SRCDIR)/ntsc -I$(SRCDIR)/../sdl -I$(SRCDIR)/../sdl/sdl1
LIBS	  = `sdl-config --libs` -lz -lm

CHDLIBDIR = $(SRCDIR)/cd_hw/libchdr
INCLUDES += -I$(CHDLIBDIR)/include -I$(CHDLIBDIR)/deps/lzma-24.05/include

BINDIR = ./bin

OBJECTS	=       $(BINDIR)/z80.o	

OBJECTS	+=     	$(BINDIR)/m68kcpu.o \
		$(BINDIR)/s68kcpu.o

OBJECTS	+=     	$(BINDIR)/genesis.o	 \
		$(BINDIR)/vdp_ctrl.o	 \
		$(BINDIR)/vdp_render.o   \
		$(BINDIR)/system.o       \
		$(BINDIR)/io_ctrl.o	 \
		$(BINDIR)/mem68k.o	 \
		$(BINDIR)/memz80.o	 \
		$(BINDIR)/membnk.o	 \
		$(BINDIR)/state.o        \
		$(BINDIR)/loadrom.o	

OBJECTS	+=      $(BINDIR)/input.o	  \
		$(BINDIR)/gamepad.o	  \
		$(BINDIR)/lightgun.o	  \
		$(BINDIR)/mouse.o	  \
		$(BINDIR)/activator.o	  \
		$(BINDIR)/xe_1ap.o	  \
		$(BINDIR)/teamplayer.o    \
		$(BINDIR)/paddle.o	  \
		$(BINDIR)/sportspad.o     \
		$(BINDIR)/terebi_oekaki.o \
		$(BINDIR)/graphic_board.o \
		$(BINDIR)/smash.o

OBJECTS	+=      $(BINDIR)/sound.o	\
		$(BINDIR)/psg.o         \
		$(BINDIR)/ym2413.o      \
		$(BINDIR)/opll.o        \
		$(BINDIR)/ym3438.o      \
		$(BINDIR)/ym2612.o    

OBJECTS	+=	$(BINDIR)/blip_buf.o 

OBJECTS	+=	$(BINDIR)/eq.o 

OBJECTS	+=      $(BINDIR)/sram.o        \
		$(BINDIR)/svp.o	        \
		$(BINDIR)/ssp16.o       \
		$(BINDIR)/ggenie.o      \
		$(BINDIR)/areplay.o	\
		$(BINDIR)/eeprom_93c.o  \
		$(BINDIR)/eeprom_i2c.o  \
		$(BINDIR)/eeprom_spi.o  \
		$(BINDIR)/flash_cfi.o   \
		$(BINDIR)/yx5200.o      \
		$(BINDIR)/sms_cart.o	\
		$(BINDIR)/md_cart.o  \
		$(BINDIR)/megasd.o 
ifeq ($(ENABLE_CDS),1)

OBJECTS +=	$(BINDIR)/scd.o	\
		$(BINDIR)/cdd.o	\
		$(BINDIR)/cdc.o	\
		$(BINDIR)/pcm.o	\
		$(BINDIR)/gfx.o	\
		$(BINDIR)/cd_cart.o
endif

OBJECTS	+=	$(BINDIR)/sms_ntsc.o	\
		$(BINDIR)/md_ntsc.o

OBJECTS	+=	$(BINDIR)/SdlUiToolkit.o \
		$(BINDIR)/Emu.o	\
		$(BINDIR)/EmuCoreInterface.o \
		$(BINDIR)/EmuUtils.o	\
		$(BINDIR)/blitter.o	\
		$(BINDIR)/config.o	\
		$(BINDIR)/error.o	\
		$(BINDIR)/unzip.o       \
		$(BINDIR)/fileio.o	
OBJECTS	+=	$(BINDIR)/bitwise.o    \
		$(BINDIR)/block.o      \
		$(BINDIR)/codebook.o   \
		$(BINDIR)/floor0.o     \
		$(BINDIR)/floor1.o     \
		$(BINDIR)/framing.o    \
		$(BINDIR)/info.o       \
		$(BINDIR)/mapping0.o   \
		$(BINDIR)/mdct.o       \
		$(BINDIR)/registry.o   \
		$(BINDIR)/res012.o     \
		$(BINDIR)/sharedbook.o \
		$(BINDIR)/synthesis.o  \
		$(BINDIR)/vorbisfile.o \
		$(BINDIR)/window.o

ifeq ($(OS),Windows_NT)
OBJECTS	+=	$(BINDIR)/icon.o
endif

all: $(BIN)

$(BIN): $(BINDIR) $(OBJECTS)
		$(CXX) $(LDFLAGS) $(OBJECTS) $(LIBS) -o $(BINDIR)/$@

$(BINDIR) :
		@[ -d $@ ] || mkdir -p $@
		
$(BINDIR)/%.o : $(SRCDIR)/%.c $(SRCDIR)/%.h
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@
	        	        
$(BINDIR)/%.o :	$(SRCDIR)/sound/%.c $(SRCDIR)/sound/%.h	        
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	$(SRCDIR)/sound/tremor/%.c 	        
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	$(SRCDIR)/input_hw/%.c $(SRCDIR)/input_hw/%.h	        
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	$(SRCDIR)/cart_hw/%.c $(SRCDIR)/cart_hw/%.h	        
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	$(SRCDIR)/cart_hw/svp/%.c      
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	$(SRCDIR)/cart_hw/svp/%.c $(SRCDIR)/cart_hw/svp/%.h	        
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	$(SRCDIR)/cd_hw/%.c $(SRCDIR)/cd_hw/%.h	        
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	$(SRCDIR)/z80/%.c $(SRCDIR)/z80/%.h	        
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	$(SRCDIR)/m68k/%.c       
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	$(SRCDIR)/ntsc/%.c $(SRCDIR)/ntsc/%.h	        
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

#$(BINDIR)/%.o :	$(CHDLIBDIR)/src/%.c 	        
#		$(CC) -c $(CFLAGS) $(INCLUDES) -I$(CHDLIBDIR)/include -I$(CHDLIBDIR)/deps/zstd-1.5.6/lib -I$(CHDLIBDIR)/deps/zstd-1.5.6/lib/common -I$(CHDLIBDIR)/deps/zlib-1.31 $< -o $@

$(BINDIR)/%.o :	$(CHDLIBDIR)/deps/lzma-24.05/src/%.c 	        
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	$(CHDLIBDIR)/deps/zstd-1.5.6/lib/common/%.c 	        
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	$(CHDLIBDIR)/deps/zstd-1.5.6/lib/decompress/%.c 	        
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	$(SRCDIR)/../sdl/%.c $(SRCDIR)/../sdl/%.h	        
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	%.cpp
		$(CXX) -c $(CXXFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

$(BINDIR)/%.o :	blitter.c 
		$(CC) -c $(CFLAGS) $(INCLUDES) $(DEFINES) $< -o $@

ifeq ($(OS),Windows_NT)
$(BINDIR)/icon.o :	
		windres $(SRCDIR)/../sdl/icon.rc $@
endif

pack	:
		strip $(BIN)
		upx -9 $(BIN)	        

clean:
	rm -f $(OBJECTS) $(BIN)


run:
	cp ../data/pixelfont-7.ttf $(BINDIR)
	cd $(BINDIR) && ./$(BIN)
